### ISSUE TITLE
Issues with authorization

### ISSUE THREAD

**Issue by saphalpdyl** [BarsatKhadka/Github-Repository-Management-System#1]
#### Problem description:
Login with username doesn't work. One tap login results in an endless network wait, and OAuth, after login, just redirects back to EasyRepo home.

#### How to reproduce?
Just login with any of the methods mentioned.

@BarsatKhadka

**Comment by BarsatKhadka** [comment]
> #### Problem description:
> 
> Login with username doesn't work. One tap login results in an endless network wait, and OAuth, after login, just redirects back to EasyRepo home.
> #### How to reproduce?
> 
> Just login with any of the methods mentioned.
> 
> [@BarsatKhadka](https://github.com/BarsatKhadka)

Yeah i have fixed the cors issue for the oauth after login and it may work,  but still the endless network wait factor will come up because the backend render hosted on free tier needs to spin up and after that neon db (which is again in sleep due to inactivity) needs to be spinned up causing issues with oauth. Login with username is not implemented yet. 

Thank you @saphalpdyl .

**Comment by saphalpdyl** [comment]
Just letting you know the issue still persists. @BarsatKhadka 😬😬

**Comment by saphalpdyl** [comment]
> Just letting you know the issue still persists. [@BarsatKhadka](https://github.com/BarsatKhadka) 😬😬

![Image](https://github.com/user-attachments/assets/fb17bfa9-0fa9-4081-89a4-b2ca86695c03)
